title = "Leap"
blurb = "Given a year, report if it is a leap year."
source = "CodeRanch Cattle Drive, Assignment 3"
source_url = "https://coderanch.com/t/718816/Leap"
deep_dive_video_url = "https://www.youtube.com/watch?v=v6fMaOdUxSk"
